dependencies:
 - python>=3.8
 - pip
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - click
 - pandas
 - openpyxl
 - bs4
 - openpyxl
 - pip:
    # for regular pip packages that conda does not accept
    - yfinance
    - make
